name: scout_obd
description: Scout OBD Application

publish_to: 'none' 

version: 0.0.2

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  comm_module:
    git:
      url: https://github.com/karthikeya-tummala-nrt/comm_module
      ref: main

  mavlink_module:
    git:
      url: https://github.com/karthikeya-tummala-nrt/mavlink_module
      ref: v0.2.5

  flutter_riverpod: ^3.3.1
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  flutter_libserialport: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  