name: Dev Release OBD

on: 
  push:
    tags:
      - 'f*-v*-alpha-*' 
  workflow_dispatch:

jobs:

  dev-release:
    runs-on: self-hosted

    env: 
      IMAGE: scout-obd
      ARM_ARCH: arm64
      X86_ARCH: x86
      TAG: ${{ github.ref_name }}

      # variable created under obd repository settings-> secrets and variables-> actions ->variables
      AVIONICS_IP: ${{ vars.AVIONICS_REGISTRY }}
      LAPTOP_IP: ${{ vars.LAPTOP_REGISTRY }}

    steps:
      
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      
       # REGISTRY CHECK STEPS
      - name: Check Avionics Registry 
        id: avionics_registry
        run: |
          if curl -fsS http://$AVIONICS_IP/v2/ >/dev/null;then
            echo "online=true" >> "$GITHUB_OUTPUT"

              if curl -fsS \
                -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
                "http://$AVIONICS_IP/v2/$IMAGE-$X86_ARCH/manifests/$TAG" > /dev/null; then

                echo "x86_exists=true" >> "$GITHUB_OUTPUT"
              
              else
                echo "x86_exists=false" >> "$GITHUB_OUTPUT"
              fi

              if curl -fsS \
                -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
                "http://$AVIONICS_IP/v2/$IMAGE-$ARM_ARCH/manifests/$TAG" > /dev/null; then

                echo "arm64_exists=true" >> "$GITHUB_OUTPUT"
              
              else
                echo "arm64_exists=false" >> "$GITHUB_OUTPUT"
              fi
          else
            echo "online=false" >> "$GITHUB_OUTPUT"
          fi

      # CHECK LAPTOP REGISTRY
      - name: Check V/V Laptop Registry 
        id: laptop_registry
        run: |
          if curl -fsS http://$LAPTOP_IP/v2/ >/dev/null;then
            echo "online=true" >> "$GITHUB_OUTPUT"

              if curl -fsS \
                -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
                "http://$LAPTOP_IP/v2/$IMAGE-$ARM_ARCH/manifests/$TAG" > /dev/null; then
                echo "exists=true" >> "$GITHUB_OUTPUT"
              
              else
                echo "exists=false" >> "$GITHUB_OUTPUT"
              fi
          else
            echo "online=false" >> "$GITHUB_OUTPUT"
          fi

      
      - name: Build x86 obd docker image and push to avionics registry
        if : |
          steps.avionics_registry.outputs.online == 'true' &&
          steps.avionics_registry.outputs.x86_exists == 'false'
        run: |

          echo "Building and pushing an x86 image: $IMAGE-$X86_ARCH:$TAG to $AVIONICS_IP"

          docker run --privileged --rm tonistiigi/binfmt --install arm64

          docker buildx build --platform linux/amd64 -t $AVIONICS_IP/$IMAGE-$X86_ARCH:$TAG --push . 
      
      - name: Build ARM64 obd docker image 
        if : |
          (
            steps.avionics_registry.outputs.online == 'true' &&
            steps.avionics_registry.outputs.arm64_exists == 'false'
          ) ||
          (
            steps.laptop_registry.outputs.online == 'true' &&
            steps.laptop_registry.outputs.exists == 'false'
          )
        run: |

          echo "Building an ARM64 image: $IMAGE-$ARM_ARCH:$TAG"

          docker buildx build --platform linux/arm64 -t $IMAGE-$ARM_ARCH:$TAG --load .
      
      - name: Push ARM image to avionics registry
        if : |
          steps.avionics_registry.outputs.online == 'true' &&
          steps.avionics_registry.outputs.arm64_exists == 'false'
        run: |
          
          echo "Image does not exist"

          echo "Pushing image to $AVIONICS_IP"

          docker tag $IMAGE-$ARM_ARCH:$TAG $AVIONICS_IP/$IMAGE-$ARM_ARCH:$TAG

          docker push $AVIONICS_IP/$IMAGE-$ARM_ARCH:$TAG
      
      - name: Push to v/v laptop registry
        if: |
          steps.laptop_registry.outputs.online == 'true' &&
          steps.laptop_registry.outputs.exists == 'false'
        run: |

          docker tag $IMAGE-$ARM_ARCH:$TAG $LAPTOP_IP/$IMAGE-$ARM_ARCH:$TAG

          docker push $LAPTOP_IP/$IMAGE-$ARM_ARCH:$TAG
