name: Dev Release OBD

on: 
  push:
    tags:
      - 'v*.*.*-rc-*' 
  workflow_dispatch:

jobs:

  dev-release:
    runs-on: self-hosted

    env: 
      IMAGE: scout-obd
      TAG: ${{ github.ref_name }}

      # variable created under obd repository settings-> secrets and variables-> actions ->variables
      AVIONICS_IP: ${{ vars.AVIONICS_REGISTRY }}
      LAPTOP_IP: ${{ vars.LAPTOP_REGISTRY }}

    steps:
      
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      
      - name: Build x86 obd docker image and push to avionics registry
        run: |
          echo "Checking registry $AVIONICS_IP to verify availability"

          if ! curl -fsS "http://$AVIONICS_IP/v2/" > /dev/null; then
            echo "Registry $REGISTRY is offline"
            echo "skipping push for this registry"
            exit 0 
          fi

          echo "Registry is online"

          echo "Checking if $IMAGE:$TAG exists"

          if curl -fsS \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            "http://$AVIONICS_IP/v2/$IMAGE/manifests/$TAG" > /dev/null; then

            echo "Image $IMAGE:$TAG already exists"
            echo "Skipping build and push"
            exit 0
          fi

          echo "Image does not exist"
          echo "Building and pushing image to $AVIONICS_IP"

          docker run --privileged --rm tonistiigi/binfmt --install arm64

          docker buildx build --platform linux/amd64 -f Dockerfile.development-amd -t scout_obd_builder:$TAG --load . \
          && docker run --rm --platform linux/amd64 -v $(pwd)/bundle:/output scout_obd_builder:$TAG \
          bash -c "cp -r /app/build/linux/amd64/release/bundle/* /output/" && docker buildx build \
          --platform linux/amd64 -t $AVIONICS_IP/$IMAGE:$TAG -f Dockerfile.production --push .

          echo "done building cleaning up builder image"
          
          docker rmi -f scout_obd_builder:$TAG
